version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
      # - npm run test:unit
      # - npm run test:functional
  build:
    commands:
      - npm run build
      - ls la
      # - docker build -t react-template:${TAG_NAME} .
  #post_build:
    #commands:
      # - scripts
      # - command
artifacts:
  files:
     - '*'
    # - location
  name: react-template-$(date +%Y-%m-%d)
  #discard-paths: yes
  base-directory: dist
