version: '3.1'

services:

  frontend:
    container_name: react-template
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      NODE_ENV: production
    networks:
      - front-tier
      - back-tier

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - back-tier

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}